color:
  brandColors:
    - '#282828'
    - '#FFFFFF'
    - '#A6A39E'
    - '#F51712'
    - '#6D738B'
  brandStrength: 0.938516
  lightness: 0.45654
  rhythmicContrast: 0.191923
  saturation: 0.452808
layout_spectrum: 0.974662
name: The House of Muse
opengraph:
  appId: 'https://www.facebook.com/thehouseofmuseoffl/'
  type: Jewellery
typography_spectrum: 0.17652
