color:
  brandColors:
    - '#DFE1DC'
    - '#D0D3CC'
    - '#000100'
    - '#BFC0BA'
    - '#ADAEA6'
  brandStrength: 0.938516
  lightness: 0.45654
  rhythmicContrast: 0.191923
  saturation: 0.452808
layout_spectrum: 0.30874529015272856
name: The House of Muse
opengraph:
  appId: 'https://www.facebook.com/thehouseofmuseoffl/'
  type: Jewellery
typography_spectrum: 0.17652
