typography_spectrum: 0.8857579817995429
color:
  brandStrength: 0.34466321975924075
  lightness: 0.2880280022509396
  saturation: 0.18382164184004068
  rhythmicContrast: 0.12618335196748376
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
opengraph:
  appId: 'https://www.facebook.com/thehouseofmuseoffl/'
  type: Jewellery
layout_spectrum: 0.5012776718940586
author:
  name: ''
  email: raunaqkhanna@hotmail.com
  url: 'https://www.instagram.com/khannaraunaq/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d2b752a9-3471-434b-a72e-6f812ed85fb4.jpg
name: The House of Muse
navigation: []
title: ''
